<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Class List</title>
    
    <style>
      @page {
            size: A4 portrait;
            margin: 20px;
        }

        body {
            font-family: Arial, sans-serif;
            background-color: #ffffff;
            margin: 10px;
            text-align: left;
        }

        h4, h5 {
            margin-bottom: 5px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            background-color: #fff;
            font-size: 14px; /* Adjust font size for fitting */
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }

        th {
            background-color: #004085;
            color: #ffffff;
            font-weight: bold;
        }

        td {
            color: #333;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        tr:hover {
            background-color: #f1f1f1;
        }

        td:first-child {
            text-align: left;
            font-weight: bold;
        }

        caption {
            font-size: 1.5em;
            font-weight: bold;
            margin-bottom: 10px;
            color: #333;
        }

        .bold-row td {
            font-weight: bold;
            background-color: #f2f2f2;
        }
    </style>
</head>

<body>
    @php
    $i = 1;
    $ay = App\Models\Academicyear::findOrFail($academic_yr);
    @endphp

    <h3>Class List for: {{$classcode}} - Semester: {{$semester}} | {{$classcampus}} </h3>
    <hh3>Intake: {{$ay->ayear}} : {{$ay->month}} | {{$ay->description}} </hh3>
    <h3>Class total: {{$count}}</h3>    
    
    <table>
        <tr>
            <th style="text-align:left;">S/N</th>
            <th style="text-align:left;">STUDENT NAME</th>
            <th>REGISTRATION#</th>
            <th>GENDER</th>
            <th>REGISTERED</th>
        </tr>
       

        @foreach($students as $stu)
           
            <tr>
                <td>{{$i++}}</td>
                <td style="text-align:left;">{{$stu->fname}} {{$stu->initials}} {{$stu->lname}}</td>
                <td>{{$stu->reg_num}}</td>
                <td>{{$stu->gender}}</td>
                <td>
                @if($stu->registered == 0)
                <span class="text-danger">Not Registered</span>
                @endif

                @if($stu->registered == 1)
                    <span class="text-warning">Pending</span>
                @endif

                @if($stu->registered == 2)
                    <span class="text-success">Registered</span>
                @endif
                </td>  
            </tr>
        @endforeach

    </table>
    <br>
    <div class="footer">
    <i>Class List Report - Generated by MCHS Students Portal @ <b>{{ now()->format('d M Y') }}.</b></i>
    </div>
   
</body>
</html>
