<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student Report</title>
    <style>
        body {
            font-family: 'Poppins', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #eef2f3;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }
        .report-container {
            max-width: 800px;
            background: #ffffff;
            padding: 20px;
            border-radius: 12px;
            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1); 
            text-align: center;
        }
        .header {
            text-align: center;
            border-bottom: 3px solid #007BFF;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .header img {
            max-width: 120px;
            margin-bottom: 10px;
        }
        .details {
            margin-bottom: 10px;
            text-align: left;
            font-size: 16px;
            color: #333;
        }
        .details p {
            margin: 2px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 12px;
            text-align: center;
            font-size: 16px;
        }
        th {
            background-color: #007BFF;
            color: #fff;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            font-style: italic;
            font-size: 14px;
            color: #555;
        }
        .signature {
            margin-top: 20px;
            text-align: left;
        }
        .signature img {
            max-width: 180px;
        }
        .school-info {
            text-align: center;
            font-size: 14px;
            color: #444;
            margin-top: -10px;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="report-container">
        <div class="header">
        <img src="{{ public_path('uploads/mchs-logo.png') }}" alt="School Logo">
            <h2>Malawi College of Health Sciences - BT</h2>
            <p><strong>Student progress report</strong></p>
            <p>P/BAG 296, Blantyre, Email: btprincipal@mchs.mw</p>
        </div>
    
        <div class="details">
            <h4>{{$student->fname}} {{$student->lname}} | {{$reg_num}}</h4>
            <p><strong>Program:</strong> {{$studentProgram}} | <strong>Class:</strong> {{$class}}, Semester: {{$semester}}</p>
            <p><strong>Intake Category:</strong> {{$ac_year}} {{$ac_month}} | {{$ac_name}}</p>
            <p><strong>Campus:</strong> {{$campus}}</p>
        </div>
        @php $i = 1; @endphp
        <table>
            <tr>
                <th>SN</th>
                <th>Module Code</th>
                <th>Module Name</th>
                <th>Grade</th>
                <th>Remarks</th>
            </tr>
            @foreach($stuSemesterSubjects as $sub)

            @php 
                $courseName = App\Models\Course::where('code', $sub->course_code)->first();
            @endphp
            <tr>
                <td>{{$i++}}</td>
                <td>{{$sub->course_code}}</td>
                <td style="text-align: left;">{{$courseName->name}}</td>
                <td>
                    @if($sub->final_grade){{$sub->final_grade}} @else -- @endif</td> 

                @if($sub->final_grade >= 50)
                <td class="Pass text-success">Pass</td>
                @elseif($sub->final_grade >= 40 && $sub->final_grade < 50)
                    <td class="Sup text-warning">Sup</td>
                @elseif($sub->final_grade < 40)
                    <td class="Repeat text-danger">  
                    @if(empty($sub->final_grade)) -- @else Repeat @endif</td>
                @endif

            </tr>
            @endforeach
        </table>
        <br>
       <br>
        <img src="{{ public_path('uploads/principal2.jpg') }}" alt="Principal's Signature" style="height: 30px; width: 680px;">
       
        <div class="footer">
     <i>Student Progress Report - Generated by MCHS Student Portal @ <b>{{ now()->format('d M Y') }}.</b></i>
    </div>
    </div>
</body>
</html>
